const fs = require("fs");

const projects = [
  ["Charge","@charge_xyz","EV charging DePIN on peaq","EV charging infrastructure for autonomous fleets, robots, and machine-driven mobility.","No approved baseline metric supplied; keep claims product-first.","EV charging is a coordination problem across power, uptime, pricing, fleets, and local operators.","closed charging networks and utility-led deployments","programmable EV charging rails","operator tools for chargers, fleets, utilization, settlement, and infrastructure monitoring","autonomous mobility and machine fleets eventually need reliable, discoverable energy access",{site:"https://charge.xyz",peaq:"https://www.peaq.xyz/"},"https://x.com/charge_xyz"],
  ["NATIX Network","@NATIXNetwork","Solana-based Physical AI mapping and camera network","Turns drive footage into road intelligence and AI training data for spatial systems.","Approved metrics: 271k+ drivers, 254M+ km mapped, and 165k+ multi-camera hours.","Physical AI needs recent road footage, edge cases, signage, traffic patterns, construction changes, and visual context from the real world.","centralized mapping fleets with expensive refresh cycles","Internet of Cameras for Physical AI","Drive& and VX360 turn vehicle cameras into contributor tools for road intelligence","camera networks can make mapping and AI data collection fresher, cheaper, and more distributed",{site:"https://www.natix.network/",whitepaper:"https://docs.natix.network/whitepaper"},"https://x.com/NATIXNetwork"],
  ["Anyone","@AnyoneFDN","Privacy DePIN","Private connectivity and bandwidth for machines, agents, and real-world networks.","Approved metrics: 7,500+ nodes and 80+ GB/s bandwidth.","Machines, agents, sensors, and users need privacy rails when physical networks move data through public infrastructure.","centralized VPNs, custodial relays, and platform-owned privacy tools","decentralized encrypted relay network","community-run relays, bandwidth supply, and privacy-first connectivity primitives","privacy can become a base requirement for agents, IoT, field devices, and machine-to-machine coordination",{site:"https://www.anyone.io/",docs:"https://docs.anyone.io/",github:"https://github.com/anyone-protocol",medium:"https://medium.com/@anyone-protocol"},"https://x.com/AnyoneFDN"],
  ["Penomo Protocol","@penomoprotocol","AI-native renewable energy finance","Financing and reporting rails for energy assets that machines and autonomous infrastructure depend on.","Approved metrics: 70% faster sourcing and 80% less manual reporting.","Infrastructure finance is slow, document-heavy, and opaque, yet energy assets need capital before machine networks can scale.","manual renewable finance workflows and private spreadsheets","AI-native infrastructure finance rails","asset sourcing, underwriting, monitoring, reporting, and financing workflows for infrastructure credit","DePIN and machine networks still depend on real energy assets, capex, reporting, and investor trust",{site:"https://penomo.com/",docs:"https://docs.penomo.com/"},"https://x.com/penomoprotocol"],
  ["BitRobot Network","@BitRobotNetwork","Embodied AI robotics challenges","Incentivizes robotics missions, benchmarks, and embodied AI development.","Approved metrics: 7 active missions and $5M prizes.","Embodied AI needs tasks, benchmarks, incentives, and real robotics progress, not only model demos in controlled environments.","closed robotics labs and isolated benchmark competitions","open robotics mission and incentive network","missions, challenges, prizes, and development loops for embodied AI builders","robotics progress improves when builders are pulled toward measurable tasks and shared problem statements",{site:"https://bitrobot.ai/"},"https://x.com/BitRobotNetwork"],
  ["Hivemapper","@Hivemapper","Decentralized mapping network","Road coverage and map freshness for autonomy, robotics, navigation, logistics, and spatial intelligence.","Approved metrics: 754M km mapped and 37% global road coverage.","Maps decay constantly. Roads change, signs move, lanes close, and logistics systems need fresher ground truth.","centralized map cars and slow refresh cycles","decentralized mapping network","dashcam contributors, road imagery, map updates, and coverage incentives","autonomy, logistics, robotics, and navigation need continuously refreshed spatial data",{site:"https://hivemapper.com/",docs:"https://docs.hivemapper.com/"},"https://x.com/Hivemapper"],
  ["ROVR Network","@ROVR_Network","LiDAR + RTK Spatial AI network","High-precision positioning and spatial data for robots, vehicles, and machine navigation.","Approved metric: 2cm positioning accuracy.","Physical AI needs precision. Robots and vehicles cannot rely on vague location when spatial tasks demand centimeter-level context.","expensive specialized surveying stacks and siloed spatial data","LiDAR and RTK spatial intelligence network","high-precision positioning, spatial data capture, and location intelligence for machine navigation","robots, vehicles, and autonomous systems need precise maps and reliable positioning in the physical world",{site:"https://rovr.network/",docs:"https://rovr-network.gitbook.io/rovr-docs"},"https://x.com/ROVR_Network"],
  ["Helium","@helium","Decentralized wireless network","Connectivity layer for sensors, machines, IoT devices, robots, and physical-world data.","Approved baseline: largest decentralized wireless network.","Physical networks need connectivity before sensors, devices, robots, and data markets can work across cities and industrial sites.","traditional telecom networks with centralized coverage economics","decentralized wireless connectivity layer","community-deployed wireless infrastructure, coverage, device connectivity, and explorer visibility","machines and sensors need connectivity that can expand through distributed supply, not only centralized capex",{site:"https://www.helium.com/",docs:"https://docs.helium.com/",explorer:"https://explorer.helium.com/"},"https://x.com/helium"],
  ["XMAQUINA","@xmaquinanetwork","DAO investing in humanoid robotics stack via peaq","Capital allocation and ownership layer for humanoid robotics and machine economy assets.","Approved metric: $35M+ treasury via peaq.","Humanoid robotics is capital-intensive, usually private, and difficult for communities to access before the largest value accrues.","closed venture funds and private robotics exposure","DAO ownership layer for humanoid robotics","treasury, governance, ownership exposure, and robotics-focused capital allocation","machine economy ownership may become as important as machine economy infrastructure",{site:"https://www.xmaquina.io/",peaq:"https://www.peaq.xyz/"},"https://x.com/xmaquinanetwork"],
  ["peaq","@peaqnetwork","Machine Economy L1","Machine identities, DePIN apps, and transaction rails for autonomous devices and real-world infrastructure.","Approved metrics: 6M+ machines onboarded and 60+ DePIN apps.","Machines need identities, transactions, permissions, data flows, and economic rails before autonomous infrastructure can coordinate at scale.","general-purpose smart contract chains not designed around machines","Layer 1 for DePIN and the Machine Economy","machine IDs, DePIN app rails, transaction infrastructure, and ecosystem coordination","DePIN apps need a base layer that understands machines, devices, and physical infrastructure patterns",{site:"https://www.peaq.xyz/",docs:"https://docs.peaq.network/"},"https://x.com/peaqnetwork"]
].map(([name,handle,cat,note,metric,truth,old,infra,prod,why,links,x])=>({name,handle,cat,note,metric,truth,old,infra,prod,why,links,x}));

const topics = {
  Charge:[
    ["Core Thesis","Charge: Why EV Charging Has To Become Machine-Readable","Charge reframes EV charging as infrastructure that machines, fleets, operators, and local networks can coordinate around.","@charge_xyz treats EV charging as machine infrastructure. Future fleets need chargers that can be discovered, priced, trusted, and coordinated, not just installed.","machine-readable energy access","charger coordination layer"],
    ["Product Deep Dive","Charge And The Operator Layer Behind EV Infrastructure","The useful part of Charge is not the slogan; it is the operator workflow needed for real charging networks.","@charge_xyz becomes interesting at the operator layer. Charging infrastructure needs visibility, pricing, uptime, usage, and incentives in one practical loop.","operator workflow","charge point operations"],
    ["Global Comparison","Charge Vs Closed EV Charging Networks","Charge is useful to study because it compares open infrastructure coordination with the closed EV charging model.","@charge_xyz sits in a bigger debate: should EV charging stay inside closed networks, or become infrastructure distributed operators can coordinate through?","open coordination versus closed fleets","distributed charging supply"]
  ],
  "NATIX Network":[
    ["Core Thesis","NATIX Network: Why Physical AI Needs An Internet Of Cameras","NATIX turns everyday cameras into a DePIN data layer for maps, road intelligence, and real-world AI training.","@NATIXNetwork is building around a Physical AI bottleneck: models need fresh real-world footage, and centralized mapping fleets cannot see everything fast enough.","real-world visual data","distributed camera network"],
    ["Product Deep Dive","NATIX VX360: When Idle Vehicle Cameras Become AI Infrastructure","VX360 shows how multi-camera vehicle footage can become useful input for mapping, simulation, and autonomy datasets.","@NATIXNetwork gets more interesting when the focus shifts from drive-to-earn to VX360: idle vehicle cameras becoming data sources for Physical AI.","multi-camera contribution","VX360 and Drive&"],
    ["Global Comparison","NATIX Vs Traditional Mapping Pipelines","NATIX competes with old mapping pipelines by activating distributed drivers instead of waiting for slow fleet refreshes.","@NATIXNetwork should be compared with mapping fleets, not only crypto projects. The question is whether distributed cameras improve freshness and coverage.","distributed coverage versus fleet scarcity","map freshness"]
  ],
  Anyone:[
    ["Core Thesis","Anyone: Privacy Infrastructure For The Machine Economy","Anyone turns privacy into a DePIN network, with independent relays supporting encrypted connectivity for users and machines.","@AnyoneFDN is not just a privacy story. In a machine economy, private connectivity becomes infrastructure for agents, devices, and sensors.","privacy as infrastructure","relay network"],
    ["Product Deep Dive","Anyone Relays: Why Bandwidth Supply Is The Product","The relay layer matters because privacy networks become useful only when independent infrastructure supplies real bandwidth.","@AnyoneFDN becomes practical at the relay level. Nodes and bandwidth matter because privacy without usable network capacity stays theoretical.","bandwidth supply","community relay operations"],
    ["Global Comparison","Anyone Vs Centralized Privacy Tools","Anyone is worth comparing with centralized VPNs because ownership, routing, and trust assumptions change completely.","@AnyoneFDN raises a clean comparison: should privacy depend on centralized providers, or on distributed relays that communities operate?","decentralized privacy versus custodial privacy","trust model"]
  ],
  "Penomo Protocol":[
    ["Core Thesis","Penomo: The Finance Layer Behind Physical Infrastructure","Penomo focuses on the slow finance layer that renewable assets and machine infrastructure need before scaling.","@penomoprotocol is interesting because DePIN still needs real financing. Energy assets need sourcing, underwriting, reporting, and trust before scaling.","infrastructure finance bottleneck","renewable credit rails"],
    ["Product Deep Dive","Penomo And The Reporting Problem In Renewable Infrastructure","Penomo becomes practical when it reduces manual reporting, because infrastructure investors need visibility before capital moves.","@penomoprotocol points at a boring but valuable problem: infrastructure finance depends on reporting, and manual reporting slows capital formation.","monitoring and reporting","AI-native asset workflows"],
    ["Global Comparison","Penomo Vs Spreadsheet-Based Infrastructure Finance","Penomo is useful to compare with private spreadsheets because infrastructure finance needs faster, auditable workflows.","@penomoprotocol should be judged against the old workflow: fragmented documents, slow diligence, private data rooms, and manual reporting.","AI-native workflows versus manual finance","capital formation"]
  ],
  "BitRobot Network":[
    ["Core Thesis","BitRobot Network: Turning Robotics Progress Into Missions","BitRobot turns robotics development into missions, incentives, and public challenges for embodied AI builders.","@BitRobotNetwork is built around a robotics problem: progress needs missions, prizes, benchmarks, and builders focused on measurable embodied tasks.","mission-based robotics progress","robotics incentive layer"],
    ["Product Deep Dive","BitRobot Missions: Why Prizes Can Move Embodied AI","BitRobot missions matter because incentives can push robotics builders toward specific problems instead of vague AI demos.","@BitRobotNetwork becomes concrete through missions. Approved references list 7 active missions and $5M prizes, making the incentive layer visible.","challenge design","active robotics missions"],
    ["Global Comparison","BitRobot Vs Closed Robotics Labs","BitRobot is interesting when compared with closed labs because it makes robotics problems more open and incentive-driven.","@BitRobotNetwork asks whether open missions and prize pools can accelerate robotics work that usually sits inside closed labs.","open missions versus closed labs","embodied AI coordination"]
  ],
  Hivemapper:[
    ["Core Thesis","Hivemapper: Map Freshness As DePIN Infrastructure","Hivemapper turns dashcam contributors into a decentralized mapping network for fresher road intelligence.","@Hivemapper matters because maps are living infrastructure. Roads change daily, and centralized fleets cannot refresh every street at machine-economy speed.","map freshness","decentralized road coverage"],
    ["Product Deep Dive","Hivemapper Contributors: Why Dashcams Become Network Supply","Hivemapper's product power comes from contributors turning everyday driving into road coverage and map updates.","@Hivemapper becomes real at the contributor level. Dashcams create supply, coverage incentives shape behavior, and map updates become network output.","contributor supply","dashcam mapping"],
    ["Global Comparison","Hivemapper Vs Centralized Map Fleets","Hivemapper's strongest comparison is with old mapping fleets: decentralized coverage competes against slow refresh cycles.","@Hivemapper should be compared with map fleets. Approved references list 754M km mapped and 37% global road coverage.","distributed mapping versus fleet mapping","global road coverage"]
  ],
  "ROVR Network":[
    ["Core Thesis","ROVR Network: Why Physical AI Needs Centimeter-Level Space","ROVR focuses on LiDAR, RTK, and high-precision spatial data for robots, vehicles, and machine navigation.","@ROVR_Network sits in a sharper Physical AI lane: machines need precise location and spatial context before they move reliably.","precision spatial data","LiDAR and RTK network"],
    ["Product Deep Dive","ROVR And The 2cm Positioning Layer","ROVR's 2cm positioning claim matters because physical machines need far more precision than consumer maps provide.","@ROVR_Network becomes practical around precision. Approved references list 2cm positioning accuracy, the kind of detail robotics workflows care about.","centimeter positioning","RTK navigation"],
    ["Global Comparison","ROVR Vs Consumer-Grade Mapping","ROVR is useful to compare with consumer maps because Physical AI needs precision, not just approximate navigation.","@ROVR_Network should be compared with consumer-grade mapping and surveying stacks. The question is whether spatial AI needs decentralized precision supply.","precision versus approximate maps","machine navigation"]
  ],
  Helium:[
    ["Core Thesis","Helium: Connectivity As Physical-World Infrastructure","Helium is the connectivity layer that shows why DePIN can matter outside dashboards and token narratives.","@helium is best understood as physical-world connectivity. Sensors, devices, and machine networks need coverage before they produce useful real-world data.","connectivity infrastructure","decentralized wireless"],
    ["Product Deep Dive","Helium Explorer: Why Coverage Must Be Visible","Helium's explorer matters because decentralized wireless networks need public visibility into coverage, activity, and infrastructure growth.","@helium becomes easier to understand through coverage visibility. The explorer turns a distributed network into something users can inspect and verify.","coverage visibility","wireless explorer"],
    ["Global Comparison","Helium Vs Traditional Telecom Buildouts","Helium is useful to compare with telecom networks because it changes who can help build coverage.","@helium asks a global infrastructure question: can wireless coverage expand through distributed contributors instead of only centralized telecom capex?","distributed coverage versus telecom capex","community-built wireless"]
  ],
  XMAQUINA:[
    ["Core Thesis","XMAQUINA: Community Ownership For The Robotics Stack","XMAQUINA brings DAO ownership logic into humanoid robotics, a sector usually dominated by private capital.","@xmaquinanetwork is not a typical DePIN infrastructure play. It is a capital and ownership experiment around humanoid robotics assets.","robotics ownership layer","DAO capital allocation"],
    ["Product Deep Dive","XMAQUINA Treasury: Why Robotics Ownership Needs Transparency","XMAQUINA's treasury matters because community ownership only works when capital allocation is visible and understandable.","@xmaquinanetwork becomes concrete through treasury transparency. Approved references mention a $35M+ treasury via peaq, making governance worth watching.","treasury transparency","robotics capital allocation"],
    ["Global Comparison","XMAQUINA Vs Traditional Robotics Funds","XMAQUINA is worth comparing with venture funds because it tests whether robotics ownership can become community-governed.","@xmaquinanetwork should be compared with private robotics funds. The difference is access, governance, and ownership structure.","community ownership versus private funds","humanoid robotics exposure"]
  ],
  peaq:[
    ["Core Thesis","peaq: Machine Identities As The DePIN Coordination Layer","peaq's core thesis is that machines need identities and transaction rails before the Machine Economy can scale.","@peaqnetwork is built around a machine-economy idea: devices need identities, apps need rails, and infrastructure needs coordination.","machine identity","DePIN coordination layer"],
    ["Product Deep Dive","peaq's DePIN App Layer: Why 60+ Apps Matter","peaq becomes stronger if its ecosystem turns machine IDs, rewards, and real-world devices into repeatable patterns.","@peaqnetwork becomes visible through its app layer. Approved references list 6M+ machines onboarded and 60+ DePIN apps.","ecosystem depth","DePIN app rails"],
    ["Global Comparison","peaq Vs Generic Smart Contract Chains","peaq's comparison is not only throughput or fees; it is specialization around machines and physical infrastructure.","@peaqnetwork should be judged against generic chains through one lens: does the network make machine coordination easier?","specialized machine rails","general purpose versus machine-first"]
  ]
};

function sections(p, t) {
  const [type,, , , focus, product] = t;
  const shared = {
    core: [
      ["The real bottleneck", `${p.truth} That is why ${focus} deserves attention as infrastructure, not as a loose crypto narrative.`, `The old model depends on ${p.old}. It can work, but it usually concentrates control and slows adaptation.`, "The important question is practical: who supplies the network, who verifies usefulness, and who pays when the output matters?", "That frame keeps the post grounded in utility instead of price speculation."],
      ["What the approved sources support", `The approved reference base supports the category, official links, and baseline facts for ${p.name}.`, `${p.metric} These details should be used as context, not as promises about token performance.`, "Readers should be able to check the claim directly from official links.", "That is why the source links stay inside the daily article, not in a hidden research note."],
      ["Why it matters for Physical AI", `${p.why}. That connects the project to robotics, autonomy, spatial intelligence, energy, privacy, or machine coordination.`, "Physical AI is not only about models. It also needs networks that collect data, move value, provide access, or coordinate devices.", "This is where DePIN becomes more than a slogan.", "It tries to turn useful physical-world participation into repeatable infrastructure supply."],
      ["Where the product becomes real", `The product anchor is ${product}. If that layer creates recurring usage, the project has a clearer reason to exist.`, "The audience should understand the workflow: contributor input, verification, useful output, buyer demand, and feedback into the network.", "That workflow is the story.", "Without it, even a strong category can collapse into vague market language."],
      ["Analyst-style takeaway", `${p.name} looks most interesting when the discussion stays close to verified infrastructure utility and away from empty hype.`, "The risk is execution: demand, quality control, incentives, regulation, and distribution can still decide whether the network compounds.", "The balanced take is simple.", `If ${focus} becomes essential to Physical AI, ${p.handle} deserves to stay on the research board.`]
    ],
    product: [
      ["The product layer to watch", `${p.name} becomes easier to judge through ${product}, because product workflows reveal whether the thesis can become daily utility.`, "A narrative can attract attention once. A workflow has to survive repeated use, operational friction, and real user expectations.", "That is the difference that matters.", "The product layer either creates a reason to return, or the market forgets the story quickly."],
      ["How the workflow should be read", "The useful mental model is input, coordination, verification, and output. Every serious DePIN project eventually has to pass through that loop.", `${p.note} This official positioning gives the article a concrete starting point.`, "The question is not whether it sounds exciting.", "The question is whether the workflow can make infrastructure cheaper, fresher, more transparent, or easier to coordinate."],
      ["Why the feature is not cosmetic", `${focus} matters because it affects the actual job the network claims to perform, not just the branding around the project.`, `Compared with ${p.old}, the DePIN version tries to widen participation and make infrastructure supply more programmable.`, "That is a real design choice.", "It changes who can contribute, how output is measured, and where network value might originate."],
      ["What still needs proof", "The proof will come from durable usage, credible demand, reliable data, and incentives that still make sense after early attention fades.", `${p.metric} Useful metrics help, but they should be treated as starting evidence rather than a finished conclusion.`, "Readers should stay demanding.", "A good DePIN story becomes stronger only when product usage and real-world demand keep repeating."],
      ["Final read", `${p.handle} should be framed as an infrastructure experiment with a specific product wedge, not as a guaranteed winner.`, `The upside is that ${p.why}. The risk is that execution may be slower and messier than the thesis sounds.`, "That is the honest angle.", `The project is worth tracking if ${product} keeps becoming more useful to real participants.`]
    ],
    global: [
      ["The old model it challenges", `${p.name} is easiest to understand when placed beside ${p.old}. That comparison gives the article a real-world anchor.`, "The traditional model often has stronger incumbents, deeper relationships, and clearer regulation, so the DePIN version has to earn attention.", "This is not automatic disruption.", "It is a test of whether distributed participation can create a better cost, coverage, freshness, or ownership curve."],
      ["What the DePIN model changes", "The DePIN angle is not simply decentralization. It is the attempt to turn distributed supply into infrastructure that someone actually needs.", `${p.infra} becomes meaningful only when contributors, users, and buyers are connected by a practical coordination loop.`, "That is the key distinction.", "A network is valuable when its output is useful beyond the group already holding the asset."],
      ["Where the comparison becomes global", `${p.why}. This is why the project belongs in a Physical AI and Machine Economy calendar.`, "Global infrastructure problems involve geography, capex, reliability, permissions, and data quality, not only software deployment.", "That complexity favors patience.", "It also makes successful DePIN networks more defensible if they solve a real supply-side problem."],
      ["The product-specific evidence", `The approved sources support ${p.name}'s category and official reference links. ${p.metric}`, `The product anchor remains ${product}. That is where readers should look before forming any strong opinion about the project.`, "Sources matter here.", "A good reader should be able to open the official links and see why this article was written."],
      ["Opinionated conclusion", `The strongest case for ${p.name} is not that it replaces the old model overnight. It explores a different infrastructure formation pattern.`, `If the network can prove demand and quality, the comparison with ${p.old} becomes more than clever framing.`, "Until then, caution is healthy.", `The right stance is interested, source-backed, and allergic to lazy hype around ${p.handle}.`]
    ]
  };
  const key = type === "Core Thesis" ? "core" : type === "Product Deep Dive" ? "product" : "global";
  return shared[key].map(([h, ...b]) => ({ h, b }));
}

const posts = [];
projects.forEach((p, pi) => topics[p.name].forEach((t) => posts.push({
  day: posts.length + 1,
  projectIndex: pi,
  type: t[0],
  title: t[1],
  preview: t[2],
  intro: t[3],
  sections: sections(p, t),
  visual: `Attach an official ${p.name} visual tied to ${t[5]}: website section, docs page, explorer view, product screen, map, dashboard, or official diagram.`,
  cta: `Which part of ${p.handle}'s thesis should be watched most closely: product usage, contributor incentives, source-backed metrics, or real buyer demand?`
})));

function runtimeMain() {
let statuses = new Array(30).fill("Ready"), currentDay = 0;
function fmtDate(i){return new Date(START.getTime()+i*86400000).toLocaleDateString("en-US",{month:"short",day:"numeric"})}
function isoDate(i){return new Date(START.getTime()+i*86400000).toISOString().slice(0,10)}
function getDay(i){const post=POSTS[i],proj=PROJECTS[post.projectIndex];return{...post,date:fmtDate(i),iso:isoDate(i),proj,bar:TYPE_COLOR[post.type]}}
function allLinks(proj){return Object.entries({...proj.links,x:proj.x})}
function articleText(d){return ["# "+d.title,"Preview: "+d.preview,"Intro: "+d.intro,...d.sections.flatMap(s=>["\n## "+s.h,...s.b.map(x=>"- "+x)]),"\nVisual suggestion: "+d.visual,"CTA: "+d.cta,"\nSources:",...allLinks(d.proj).map(([k,v])=>"- "+k+": "+v),"#DePIN #PhysicalAI #MachineEconomy","Not financial advice."].join("\n")}
function articleHtml(d){return "<h1>"+d.title+"</h1><p><strong>Preview:</strong> "+d.preview+"</p><p><strong>Intro:</strong> "+d.intro+"</p>"+d.sections.map(s=>"<h2>"+s.h+"</h2><ul>"+s.b.map(x=>"<li>"+x+"</li>").join("")+"</ul>").join("")+"<p><strong>Visual suggestion:</strong> "+d.visual+"</p><p><strong>CTA:</strong> "+d.cta+"</p><p><strong>Sources:</strong></p><ul>"+allLinks(d.proj).map(([k,v])=>"<li>"+k+": <a href=\""+v+"\" target=\"_blank\">"+v+"</a></li>").join("")+"</ul><p>#DePIN #PhysicalAI #MachineEconomy</p><p>Not financial advice.</p>"}
function sourceRows(proj){return allLinks(proj).map(([k,v])=>"<div class=\"src-row\"><span class=\"src-name\">"+proj.name+"</span><span class=\"src-type\">"+k+"</span><a href=\""+v+"\" target=\"_blank\">"+v+"</a></div>").join("")}
function validation(d){const previewWords=d.preview.trim().split(/\s+/).length,introLen=d.intro.length,sectionCount=d.sections.length,minBullets=Math.min(...d.sections.map(s=>s.b.length));return["<span class=\"val-chip "+(previewWords<=20?"val-ok":"val-warn")+"\">"+previewWords+"/20-word preview</span>","<span class=\"val-chip "+(introLen<=250?"val-ok":"val-warn")+"\">"+introLen+"/250 intro chars</span>","<span class=\"val-chip "+(sectionCount>=4?"val-ok":"val-warn")+"\">"+sectionCount+" subheadings</span>","<span class=\"val-chip "+(minBullets>=3?"val-ok":"val-warn")+"\">"+minBullets+"+ bullets/section</span>","<span class=\"val-chip val-ok\">Sources linked</span>","<span class=\"val-chip "+(d.intro.includes(d.proj.handle)?"val-ok":"val-warn")+"\">Project tagged</span>"].join("")}
function renderCalendar(){const grid=document.getElementById("cal-grid");grid.innerHTML="";let posted=0,ready=0;for(let i=0;i<30;i++){const d=getDay(i);if(statuses[i]==="Posted")posted++;if(statuses[i]==="Ready")ready++;const card=document.createElement("div");card.className="day-card";card.onclick=()=>openModal(i);card.innerHTML="<div class=\"left-bar\" style=\"background:"+d.bar+"\"></div><div class=\"inner\"><div class=\"top-row\"><div><div class=\"day-num\">"+String(d.day).padStart(2,"0")+"</div><div class=\"date-lbl\">"+d.date+"</div></div><span class=\"type-badge type-"+d.type.replaceAll(" ","-")+"\">"+d.type+"</span></div><div class=\"project\">"+d.proj.name+" ("+d.proj.handle+")</div><div class=\"angle\">"+d.title+"</div><div class=\"bottom-row\"><span class=\"status-chip status-"+statuses[i]+"\">"+statuses[i]+"</span><span class=\"time-lbl\">18:00 IST</span><span class=\"src-count\">"+(Object.keys(d.proj.links).length+1)+" src</span></div><div class=\"action-row\"><button class=\"btn-tiny accent\" onclick=\"event.stopPropagation();openModal("+i+")\">View full article</button><button class=\"btn-tiny\" onclick=\"event.stopPropagation();copyArticle("+i+")\">Copy</button></div></div>";grid.appendChild(card)}document.getElementById("stat-posted").textContent=posted;document.getElementById("stat-ready").textContent=ready}
function openModal(i){currentDay=i;const d=getDay(i);document.getElementById("m-day").textContent=String(d.day).padStart(2,"0");document.getElementById("m-project").textContent=d.proj.name+" ("+d.proj.handle+")";document.getElementById("m-angle").textContent=d.title;document.getElementById("m-badges").innerHTML="<span class=\"type-badge type-"+d.type.replaceAll(" ","-")+"\">"+d.type+"</span><span class=\"status-chip status-"+statuses[i]+"\">"+statuses[i]+"</span><span class=\"time-lbl\">"+d.date+" - 18:00 IST</span>";document.getElementById("m-article").innerHTML=articleHtml(d);document.getElementById("m-validation").innerHTML=validation(d);document.getElementById("m-sources").innerHTML=sourceRows(d.proj);document.getElementById("m-cal-title").textContent="Post on X: Day "+d.day+" - "+d.type+" - "+d.proj.name;document.getElementById("m-cal-desc").textContent=d.iso+" at 18:00 IST. Manual X posting reminder. Full final article and sources are embedded in this dashboard.";document.getElementById("m-email-subject").textContent="6 PM: Your edge disappears if you skip Day "+d.day+" - "+d.proj.name;document.getElementById("m-email-body").textContent="From "+SENDER+" to "+RECIPIENT+". Open the dashboard, copy the final article, attach the suggested official visual, and post manually on X.";document.getElementById("modal-wrap").classList.add("open")}
function closeModal(e){if(!e||e.target===document.getElementById("modal-wrap"))document.getElementById("modal-wrap").classList.remove("open")}
function showPanel(id,el){document.querySelectorAll(".panel").forEach(p=>p.classList.remove("active"));document.querySelectorAll(".tab").forEach(t=>t.classList.remove("active"));document.getElementById("panel-"+id).classList.add("active");if(el)el.classList.add("active")}
function renderToday(){const d=getDay(0);document.getElementById("today-project").textContent=d.proj.name+" ("+d.proj.handle+")";document.getElementById("today-angle").textContent=d.title;document.getElementById("today-badges").innerHTML="<span class=\"type-badge type-"+d.type.replaceAll(" ","-")+"\">"+d.type+"</span><span class=\"status-chip status-"+statuses[0]+"\">"+statuses[0]+"</span>";document.getElementById("today-article").innerHTML=articleHtml(d);document.getElementById("today-validation").innerHTML=validation(d);document.getElementById("today-sources").innerHTML=sourceRows(d.proj)}
function copyArticle(i){navigator.clipboard.writeText(articleText(getDay(i))).catch(()=>{})}function copyModalArticle(){copyArticle(currentDay)}function copyTodayArticle(){copyArticle(0)}
function copyModalSources(){const d=getDay(currentDay);navigator.clipboard.writeText(allLinks(d.proj).map(([k,v])=>k+": "+v).join("\n")).catch(()=>{})}function copyTodaySources(){const d=getDay(0);navigator.clipboard.writeText(allLinks(d.proj).map(([k,v])=>k+": "+v).join("\n")).catch(()=>{})}
function markPosted(i){statuses[i]="Posted";renderCalendar();renderToday()}function markPostedModal(){markPosted(currentDay);openModal(currentDay)}
const SOURCE_DATA={official:PROJECTS.map(p=>({name:p.name,type:"Website",url:p.links.site,checked:"Embedded",used:3})),docs:PROJECTS.flatMap(p=>Object.entries(p.links).filter(([k])=>["docs","whitepaper"].includes(k)).map(([k,v])=>({name:p.name,type:k,url:v,checked:"Embedded",used:3}))),explorers:PROJECTS.flatMap(p=>Object.entries(p.links).filter(([k])=>["explorer","peaq"].includes(k)).map(([k,v])=>({name:p.name,type:k,url:v,checked:"Embedded",used:2}))),blogs:PROJECTS.flatMap(p=>Object.entries(p.links).filter(([k])=>["medium"].includes(k)).map(([k,v])=>({name:p.name,type:k,url:v,checked:"Embedded",used:1}))),community:PROJECTS.flatMap(p=>Object.entries(p.links).filter(([k])=>["github"].includes(k)).map(([k,v])=>({name:p.name,type:k,url:v,checked:"Embedded",used:1}))),social:PROJECTS.map(p=>({name:p.name,type:"X",url:p.x,checked:"Embedded",used:3}))};
function showSourceTab(tab,el){document.querySelectorAll(".stab").forEach(t=>t.classList.remove("active"));if(el)el.classList.add("active");renderSources(tab)}
function renderSources(tab="official"){const rows=SOURCE_DATA[tab]||[];document.getElementById("source-content").innerHTML="<table class=\"source-table\"><thead><tr><th>Project</th><th>Type</th><th>Link</th><th>Last checked</th><th>Posts</th></tr></thead><tbody>"+rows.map(r=>"<tr><td>"+r.name+"</td><td><span class=\"pill\">"+r.type+"</span></td><td><a href=\""+r.url+"\" target=\"_blank\">"+r.url+"</a></td><td>"+r.checked+"</td><td>"+r.used+"</td></tr>").join("")+"</tbody></table>"}
function renderCoverage(){document.getElementById("proj-grid").innerHTML=PROJECTS.map((p,i)=>"<div class=\"proj-card\"><div class=\"proj-top\"><span class=\"handle\">"+p.handle+"</span><span class=\"cat-badge\">"+p.cat.split("/")[0].trim()+"</span></div><div class=\"proj-name\">"+p.name+"</div><div class=\"proj-note\">"+p.note+"</div><div class=\"coverage-bar\"><div class=\"coverage-fill\" style=\"width:100%\"></div></div><div class=\"proj-stats\"><div class=\"proj-stat\">Articles: <span>3</span></div><div class=\"proj-stat\">Days: <span>"+(i*3+1)+"-"+(i*3+3)+"</span></div></div><div class=\"proj-links\">"+Object.entries(p.links).slice(0,4).map(([k,v])=>"<a class=\"proj-link\" href=\""+v+"\" target=\"_blank\">"+k+"</a>").join("")+"</div></div>").join("")}
function downloadICS(){let ics="BEGIN:VCALENDAR\nVERSION:2.0\nPRODID:-//FDV OPS//DePIN Creator Calendar//EN\nCALSCALE:GREGORIAN\nMETHOD:PUBLISH\n";for(let i=0;i<30;i++){const d=getDay(i),compact=d.iso.replaceAll("-","");ics+="BEGIN:VEVENT\nUID:fdv-ops-day-"+d.day+"@depin-calendar\nDTSTAMP:20260609T123000Z\nDTSTART;TZID=Asia/Kolkata:"+compact+"T180000\nDTEND;TZID=Asia/Kolkata:"+compact+"T183000\nSUMMARY:Post on X: Day "+d.day+" - "+d.proj.name+"\nDESCRIPTION:Open FDV OPS Day "+String(d.day).padStart(2,"0")+". Copy the full embedded article, attach the suggested visual, and post manually on X.\nEND:VEVENT\n"}ics+="END:VCALENDAR";const blob=new Blob([ics],{type:"text/calendar"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="depin_30_day_calendar.ics";a.click();URL.revokeObjectURL(a.href)}
Object.assign(globalThis,{showPanel,closeModal,openModal,copyArticle,copyModalArticle,copyTodayArticle,copyModalSources,copyTodaySources,markPosted,markPostedModal,showSourceTab,downloadICS});renderCalendar();renderToday();renderSources();renderCoverage();
}

const app = `const START=new Date("2026-06-10T00:00:00+05:30"),SENDER="aarkay.4153@gmail.com",RECIPIENT="aarkay.34429@protonmail.com";
const TYPE_COLOR={"Core Thesis":"var(--long)","Product Deep Dive":"var(--article)","Global Comparison":"var(--thread)"};
const PROJECTS=${JSON.stringify(projects,null,2)};
const POSTS=${JSON.stringify(posts,null,2)};
(${runtimeMain.toString()})();`;
fs.writeFileSync("app.js", app, "utf8");

for (const file of ["index.html","fdv_ops_dashboard.html"]) {
  let html = fs.readFileSync(file, "utf8");
  html = html.replace(/<script>[\s\S]*?<\/script>\s*<\/body>/, '<script src="app.js"></script>\n</body>');
  html = html.replace("Source Library <span class=\"sub\">Embedded offline facts, source links retained</span>", "Source Library <span class=\"sub\">Embedded sources for the finished articles</span>");
  html = html.replace("Title, 20-word preview, 250-character intro, 5 sections, 15 bullets", "Title, 20-word preview, 250-character intro, 5 sections, 20 bullets");
  fs.writeFileSync(file, html, "utf8");
}

const md = `# FDV OPS 30-Day DePIN Article Calendar

This calendar contains 30 finished long-form X Article drafts, not post ideas.

## Structure

- 10 projects x 3 finished articles each
- Every day includes the complete article body
- Each article includes a title, 20-word preview, tagged intro under 250 characters, 5 subheadings, bullets, visual suggestion, CTA, source links, hashtags, and NFA
- Daily reminder time: 18:00 IST
- Posting to X remains manual

## Projects

${projects.map((p,i)=>`${i+1}. ${p.name} (${p.handle}) - Days ${i*3+1}-${i*3+3}`).join("\n")}

## Live dashboard

https://aarkay4153-code.github.io/fdv-ops-calendar/
`;
fs.writeFileSync("depin_30_day_calendar.md", md, "utf8");

console.log(`Generated ${posts.length} finished articles.`);
